# Generated by Django 5.0.7 on 2024-07-26 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='firstname',
        ),
    ]
