# Generated by Django 5.0.6 on 2024-08-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('cost', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('elligible', models.CharField(default='all', max_length=500)),
                ('effective_date', models.DateField(default='07-11-2013')),
                ('expiration_date', models.DateField()),
            ],
            options={
                'db_table': 'Benefit',
            },
        ),
        migrations.CreateModel(
            name='Enrollement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.EmailField(default='123@gmail.com', max_length=254)),
                ('ename', models.CharField(default='', max_length=200)),
                ('cost', models.IntegerField(default=0)),
                ('bid', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('Request', models.CharField(default='no request', max_length=200)),
                ('expiration_date', models.DateField()),
                ('Request_date', models.DateField(auto_now=True)),
                ('enrollement_date', models.DateField(default='2000-11-11')),
                ('state', models.CharField(default='no request', max_length=200)),
                ('type', models.CharField(default='Other', max_length=200)),
                ('detail', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bid', models.IntegerField(default=0)),
                ('user', models.CharField(default='', max_length=200)),
                ('ename', models.CharField(default='', max_length=200)),
                ('Request', models.CharField(default='no request', max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
