# Generated by Django 5.0.7 on 2024-07-26 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together={('employee', 'month')},
        ),
    ]
