# Generated by Django 5.0.7 on 2024-07-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancerecord_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together=set(),
        ),
    ]
